---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ISLR)
library(glmnet)
library(dplyr)
library(tidyr)
library(readr)
appliances = read.csv("energydata_complete.csv")
```

```{r}
appliances_data = na.omit(appliances)
appliances_data$date<- NULL
summary(appliances_data)
```

```{r}
set.seed(1)
train = appliances_data %>%
sample_frac(0.5)
test = appliances_data %>%
setdiff(train)
```

```{r}
#pcr model
library(pls)
pcr_mod=pcr(Appliances~.,data=train,scale=TRUE,validation="CV")
pcr_pred=predict(pcr_mod,test,ncomp=pcr_mod$ncomp)
mean((test$Appliances-pcr_pred)^2)
# Plot the root mean squared error
validationplot(pcr_mod)
# Plot the cross validation MSE
validationplot(pcr_mod, val.type="MSEP")
predplot(pcr_mod)
coefplot(pcr_mod)
summary(pcr_mod)
```

```{r}
#pls model
library(pls)
pls_mod=pcr(Appliances~.,data=train,scale=TRUE,validation="CV")
pls_pred=predict(pls_mod,test,ncomp=pls_mod$ncomp)
mean((test$Appliances-pls_pred)^2)
# Plot the root mean squared error
validationplot(pls_mod)
# Plot the cross validation MSE
validationplot(pls_mod, val.type="MSEP")
predplot(pls_mod)
coefplot(pls_mod)
summary(pls_mod)
```